#!/usr/bin/env bash
# ============================================================
# install.sh — bootstrap for the multi-account dev environment
# (GitHub + Claude Code per directory)
#
# Idempotent: run it as many times as you want.
# Usage:  git clone git@github.com:YOU/switchcraft.git && cd switchcraft && ./install.sh
# ============================================================
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$REPO_DIR/setup.conf"

info()  { printf "\033[1;34m==>\033[0m %s\n" "$*"; }
ok()    { printf "\033[1;32m ✓\033[0m %s\n" "$*"; }
warn()  { printf "\033[1;33m !\033[0m %s\n" "$*"; }

# ------------------------------------------------------------
# 0. Detect shell rc
# ------------------------------------------------------------
SHELL_RC="$HOME/.bashrc"
[[ "${SHELL:-}" == *zsh* ]] && SHELL_RC="$HOME/.zshrc"

# ------------------------------------------------------------
# 1. direnv
# ------------------------------------------------------------
info "Checking direnv..."
if ! command -v direnv >/dev/null 2>&1; then
  if command -v brew >/dev/null 2>&1; then
    brew install direnv || warn "Failed to install direnv via brew"
  elif command -v sudo >/dev/null 2>&1 && command -v apt-get >/dev/null 2>&1; then
    sudo apt-get install -y direnv || warn "Failed to install direnv via apt"
  else
    warn "Install direnv manually: https://direnv.net/docs/installation.html"
  fi
fi
if command -v direnv >/dev/null 2>&1; then
  HOOK_LINE='eval "$(direnv hook '"$(basename "${SHELL:-bash}")"')"'
  grep -qF "direnv hook" "$SHELL_RC" 2>/dev/null || {
    printf "\n# direnv (switchcraft)\n%s\n" "$HOOK_LINE" >> "$SHELL_RC"
    ok "direnv hook added to $SHELL_RC"
  }
fi

# ------------------------------------------------------------
# 2. SSH keys (generated per machine — NEVER versioned)
# ------------------------------------------------------------
info "Checking SSH keys..."
mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh"
gen_key() {
  local slug="$1" email="$2" keyfile="$HOME/.ssh/id_ed25519_$1"
  if ! command -v ssh-keygen >/dev/null 2>&1; then
    warn "ssh-keygen not found; install openssh-client and run again."
    return 0
  fi
  if [[ ! -f "$keyfile" ]]; then
    ssh-keygen -t ed25519 -C "$email" -f "$keyfile" -N ""
    ok "Key created: $keyfile"
    warn "Add the public key below to the corresponding GitHub account:"
    echo "------------------------------------------------------------"
    cat "$keyfile.pub"
    echo "------------------------------------------------------------"
  else
    ok "Key already exists: $keyfile"
  fi
}
gen_key "$A_SLUG" "$A_GIT_EMAIL"
gen_key "$B_SLUG" "$B_GIT_EMAIL"

# ------------------------------------------------------------
# 3. Git: profiles + conditional include per directory
# ------------------------------------------------------------
info "Configuring git profiles..."
render() { # render <template> <destination> — substitutes {{VARS}}
  local tpl="$1" dst="$2"
  sed -e "s|{{PROJECTS_ROOT}}|$PROJECTS_ROOT|g" \
      -e "s|{{A_SLUG}}|$A_SLUG|g"   -e "s|{{B_SLUG}}|$B_SLUG|g" \
      -e "s|{{A_NAME}}|$A_GIT_NAME|g" -e "s|{{B_NAME}}|$B_GIT_NAME|g" \
      -e "s|{{A_EMAIL}}|$A_GIT_EMAIL|g" -e "s|{{B_EMAIL}}|$B_GIT_EMAIL|g" \
      -e "s|{{HOME}}|$HOME|g" \
      "$tpl" > "$dst"
}

mkdir -p "$HOME/.config/git-profiles"
render "$REPO_DIR/templates/gitconfig-profile-a" "$HOME/.config/git-profiles/$A_SLUG"
render "$REPO_DIR/templates/gitconfig-profile-b" "$HOME/.config/git-profiles/$B_SLUG"

# Includes block in ~/.gitconfig (between markers, so it's re-runnable)
GITCONFIG="$HOME/.gitconfig"
touch "$GITCONFIG"
TMP="$(mktemp)"
awk '/# >>> switchcraft >>>/{skip=1} /# <<< switchcraft <<</{skip=0; next} !skip' "$GITCONFIG" > "$TMP"
cat >> "$TMP" <<EOF
# >>> switchcraft >>>
[includeIf "gitdir:$PROJECTS_ROOT/$A_SLUG/"]
    path = $HOME/.config/git-profiles/$A_SLUG
[includeIf "gitdir:$PROJECTS_ROOT/$B_SLUG/"]
    path = $HOME/.config/git-profiles/$B_SLUG
# <<< switchcraft <<<
EOF
mv "$TMP" "$GITCONFIG"
ok "Conditional includes written to ~/.gitconfig"

# ------------------------------------------------------------
# 4. Project structure + .envrc (Claude Code per directory)
# ------------------------------------------------------------
info "Creating project structure and .envrc..."
for SLUG in "$A_SLUG" "$B_SLUG"; do
  DIR="$PROJECTS_ROOT/$SLUG"
  mkdir -p "$DIR" "$HOME/.claude-$SLUG"
  cat > "$DIR/.envrc" <<EOF
# Generated by switchcraft — account: $SLUG
export CLAUDE_CONFIG_DIR=\$HOME/.claude-$SLUG
EOF
  command -v direnv >/dev/null 2>&1 && direnv allow "$DIR" >/dev/null 2>&1 || true
  ok "$DIR ready (.envrc + ~/.claude-$SLUG)"
done

# ------------------------------------------------------------
# 5. Summary / next manual steps
# ------------------------------------------------------------
cat <<EOF

============================================================
 Setup complete. Manual steps (once per machine):
============================================================
 1. Add the public keys to the GitHub accounts:
      ~/.ssh/id_ed25519_$A_SLUG.pub  → account $A_GITHUB_USER
      ~/.ssh/id_ed25519_$B_SLUG.pub  → account $B_GITHUB_USER
    Test:  ssh -i ~/.ssh/id_ed25519_$A_SLUG -o IdentitiesOnly=yes -T git@github.com

 2. Log in to Claude Code in each profile:
      CLAUDE_CONFIG_DIR=~/.claude-$A_SLUG claude   # login account A
      CLAUDE_CONFIG_DIR=~/.claude-$B_SLUG claude   # login account B

 3. Reopen the terminal (so the direnv hook loads).

 After that: any repo inside
   $PROJECTS_ROOT/$A_SLUG  → commits and uses Claude as account A
   $PROJECTS_ROOT/$B_SLUG  → commits and uses Claude as account B
============================================================
EOF
